export const apiUrl = 'https://gourmet-indol.vercel.app/api'
export const ACCOUNT_ID = 'accountId'
export const ROLE = 'role'
export const ACCESS_TOKEN = 'accessToken'
export const PROFILE_INFORMATION = 'profile_information'
export const USERNAME = 'username'